# Microservice
server:
  port: 8080
  servlet:
    context-path: /identity

# Spring config
spring:
  application:
    name: zerotohero

  # load .env file
  config:
    import: optional:file:.env[.properties]

  # Database
  datasource:
    url: ${DBMS_CONNECTION}
    username: ${DBMS_USERNAME}
    password: ${DBMS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  signer_key: ${API_KEY}
  issuer: https://lamnd.com
  access_token_expiration: 3600 # seconds (1 hour)
  refresh_token_expiration: 86400 # seconds (24 hours)